### ISSUE TITLE
Need CDK V2 version of this example.

### ISSUE THREAD

**Issue by yangliunewyork** [aws-samples/automate-cross-account-cicd-cfn-cdk#8]
Some comments:

- The example here is using CDK v1, which entered maintenance on June 1, 2022 and will reach end-of-life on June 1, 2023. https://docs.aws.amazon.com/cdk/v2/guide/migrating-v2.html
- We probably don't want use a mixture of CloudFormation to set up the roles and CDK to setup the infrastructure. Probably better stick with CDK when it comes to create the needed cross account roles and permissions. It seems that CDK v2 have some naive support for cross account roles, so the roles creation here may not be needed any more.

**Comment by natalie-white-aws** [comment]
Finally upgraded to CDK v2 due to critical security vulnerabilities. 

If you watch the video of the re:Invent 2021 presentation linked in the README, you'll see that we're telling the story of the IAM roles being managed by a different team. Of course you could create a different stack with the roles and deploy it via yet another CDK pipeline, but if they don't change frequently, using CloudFormation is sufficient and it's not worth the overhead of keeping another CI/CD pipeline just for the roles. At the end of the day, the entire solution is deployed via CloudFormation anyway. :) 

Thanks again for commenting - I'll close this out.
